# @package _global_
defaults:
    - override /datasets: toto

tokenizers:
    observations:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    actions:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    rewards:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create


dataset:
    path: "../../../data_check.pkl"


args:
    mask_ratios: [0.4, 0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95, 1.0]

wandb:
    project: "toto_test"
    resume: allow
