default:
    - override hydra/output: local
    - override hydra/launcher: local

data:
  pickle_fn: assets/cloud-dataset-scooping/scooping_parsed_with_embeddings_moco_conv5-004.pkl
  subsample_period: 20
  in_dim: 7
  out_dim: 7
  H: 60 # horizon of actions to predict each time
  top_k: null
  images:
    cameras: [] #["cam0d"]
    im_h: 480
    im_w: 640
    per_img_out: 128
    crop: True
  noise: 0.0

agent:
  type: 'collaborator_agent'
  vision_model: 'moco_conv5_robocloud'
  # TODO (Optional): If you use a custom vision_model, optionally specify the path to your model here
  # vision_model_path won't be used if you use an existing TOTO vision_model.
  # TODO (Optional): additional keys (if any) for initializing your vision model should go here. 
  vision_model_path: assets/moco_conv5_robocloud.pth 
  description: NA
  # hidden_dim: 128

  n_layer: 3
  n_head: 1
  d_model: 128
  d_head: 128
  d_inner: 128
  dropout: 0.2 
  dropatt: 0.05
  MEM_LEN: 15
  ext_len: 0
  num_mem_tokens: 15 
  mem_at_end: True
  learning_rate: 0.01
  context_length: 20
  sections: 3
  grad_norm_clip: 1.0
  fix_resnet: False

training:
  lr: 1e-3
  seed: 0
  epochs: 80
  device: 'cuda:3'
  batch_size: 4
  save_every_x_epoch: 10

debug: False
